#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ksonnet
Version  : 0.13.1
Release  : 1
URL      : https://github.com/ksonnet/ksonnet/archive/v0.13.1.tar.gz
Source0  : https://github.com/ksonnet/ksonnet/archive/v0.13.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-3.0 CC-BY-SA-4.0 CDDL-1.0 ISC MIT MPL-2.0-no-copyleft-exception WTFPL
Requires: ksonnet-bin = %{version}-%{release}
Requires: ksonnet-license = %{version}-%{release}
BuildRequires : buildreq-golang

%description
This is a work-in-progress HTTP/2 implementation for Go.
It will eventually live in the Go standard library and won't require
any changes to your code to use.  It will just be automatic.

%package bin
Summary: bin components for the ksonnet package.
Group: Binaries
Requires: ksonnet-license = %{version}-%{release}

%description bin
bin components for the ksonnet package.


%package license
Summary: license components for the ksonnet package.
Group: Default

%description license
license components for the ksonnet package.


%prep
%setup -q -n ksonnet-0.13.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548729066
## make_prepend content
export GOPATH=/go
mkdir -p /go/src/github.com/ksonnet
ln -s /builddir/build/BUILD/ksonnet-0.13.1 /go/src/github.com/ksonnet/ksonnet
cd /go/src/github.com/ksonnet/ksonnet
## make_prepend end
make  %{?_smp_mflags} install


%install
export SOURCE_DATE_EPOCH=1548729066
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ksonnet
cp LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/LICENSE
cp vendor/cloud.google.com/go/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_cloud.google.com_go_LICENSE
cp vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_Azure_go-ansiterm_LICENSE
cp vendor/github.com/Azure/go-autorest/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_Azure_go-autorest_LICENSE
cp vendor/github.com/BurntSushi/toml/COPYING %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_COPYING
cp vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_toml-test-decoder_COPYING
cp vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_toml-test-encoder_COPYING
cp vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_tomlv_COPYING
cp vendor/github.com/GeertJohan/go.rice/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_GeertJohan_go.rice_LICENSE
cp vendor/github.com/MakeNowJust/heredoc/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_MakeNowJust_heredoc_LICENSE
cp vendor/github.com/Masterminds/semver/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_Masterminds_semver_LICENSE.txt
cp vendor/github.com/Masterminds/sprig/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_Masterminds_sprig_LICENSE.txt
cp vendor/github.com/PuerkitoBio/purell/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_PuerkitoBio_purell_LICENSE
cp vendor/github.com/PuerkitoBio/urlesc/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_PuerkitoBio_urlesc_LICENSE
cp vendor/github.com/aokoli/goutils/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_aokoli_goutils_LICENSE.txt
cp vendor/github.com/asaskevich/govalidator/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_asaskevich_govalidator_LICENSE
cp vendor/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_beorn7_perks_LICENSE
cp vendor/github.com/blang/semver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_blang_semver_LICENSE
cp vendor/github.com/cenkalti/backoff/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_cenkalti_backoff_LICENSE
cp vendor/github.com/cpuguy83/go-md2man/LICENSE.md %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
cp vendor/github.com/daaku/go.zipexe/license %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_daaku_go.zipexe_license
cp vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_davecgh_go-spew_LICENSE
cp vendor/github.com/dgrijalva/jwt-go/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_dgrijalva_jwt-go_LICENSE
cp vendor/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_distribution_LICENSE
cp vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_LICENSE
cp vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_NOTICE
cp vendor/github.com/docker/docker/contrib/syntax/vim/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_contrib_syntax_vim_LICENSE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
cp vendor/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_go-connections_LICENSE
cp vendor/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_go-units_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_spdystream_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE.docs %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_docker_spdystream_LICENSE.docs
cp vendor/github.com/emicklei/go-restful-swagger12/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_emicklei_go-restful-swagger12_LICENSE
cp vendor/github.com/emicklei/go-restful/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_emicklei_go-restful_LICENSE
cp vendor/github.com/evanphx/json-patch/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_evanphx_json-patch_LICENSE
cp vendor/github.com/exponent-io/jsonpath/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_exponent-io_jsonpath_LICENSE
cp vendor/github.com/fatih/camelcase/LICENSE.md %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_fatih_camelcase_LICENSE.md
cp vendor/github.com/fatih/color/LICENSE.md %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_fatih_color_LICENSE.md
cp vendor/github.com/fsnotify/fsnotify/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_fsnotify_fsnotify_LICENSE
cp vendor/github.com/ghodss/yaml/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_ghodss_yaml_LICENSE
cp vendor/github.com/go-openapi/analysis/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_analysis_LICENSE
cp vendor/github.com/go-openapi/errors/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_errors_LICENSE
cp vendor/github.com/go-openapi/jsonpointer/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_jsonpointer_LICENSE
cp vendor/github.com/go-openapi/jsonreference/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_jsonreference_LICENSE
cp vendor/github.com/go-openapi/loads/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_loads_LICENSE
cp vendor/github.com/go-openapi/runtime/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_runtime_LICENSE
cp vendor/github.com/go-openapi/runtime/middleware/denco/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_runtime_middleware_denco_LICENSE
cp vendor/github.com/go-openapi/spec/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_spec_LICENSE
cp vendor/github.com/go-openapi/spec/license.go %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_spec_license.go
cp vendor/github.com/go-openapi/strfmt/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_strfmt_LICENSE
cp vendor/github.com/go-openapi/swag/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_swag_LICENSE
cp vendor/github.com/go-openapi/validate/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_validate_LICENSE
cp vendor/github.com/gobwas/glob/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_gobwas_glob_LICENSE
cp vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_gogo_protobuf_LICENSE
cp vendor/github.com/golang/glog/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_golang_glog_LICENSE
cp vendor/github.com/golang/groupcache/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_golang_groupcache_LICENSE
cp vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_golang_protobuf_LICENSE
cp vendor/github.com/google/btree/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_btree_LICENSE
cp vendor/github.com/google/go-github/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-github_LICENSE
cp vendor/github.com/google/go-jsonnet/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-jsonnet_LICENSE
cp vendor/github.com/google/go-querystring/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-querystring_LICENSE
cp vendor/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_gofuzz_LICENSE
cp vendor/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_google_uuid_LICENSE
cp vendor/github.com/googleapis/gnostic/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_googleapis_gnostic_LICENSE
cp vendor/github.com/gophercloud/gophercloud/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_gophercloud_gophercloud_LICENSE
cp vendor/github.com/gregjones/httpcache/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_gregjones_httpcache_LICENSE.txt
cp vendor/github.com/hashicorp/golang-lru/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_hashicorp_golang-lru_LICENSE
cp vendor/github.com/hashicorp/hcl/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_hashicorp_hcl_LICENSE
cp vendor/github.com/howeyc/gopass/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_howeyc_gopass_LICENSE.txt
cp vendor/github.com/howeyc/gopass/OPENSOLARIS.LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_howeyc_gopass_OPENSOLARIS.LICENSE
cp vendor/github.com/huandu/xstrings/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_huandu_xstrings_LICENSE
cp vendor/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_imdario_mergo_LICENSE
cp vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_inconshreveable_mousetrap_LICENSE
cp vendor/github.com/jonboulle/clockwork/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_jonboulle_clockwork_LICENSE
cp vendor/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_json-iterator_go_LICENSE
cp vendor/github.com/kardianos/osext/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_kardianos_osext_LICENSE
cp vendor/github.com/ksonnet/ksonnet-lib/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_ksonnet_ksonnet-lib_LICENSE
cp vendor/github.com/magiconair/properties/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_magiconair_properties_LICENSE
cp vendor/github.com/mailru/easyjson/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_mailru_easyjson_LICENSE
cp vendor/github.com/mattn/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_mattn_go-colorable_LICENSE
cp vendor/github.com/mattn/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_mattn_go-isatty_LICENSE
cp vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
cp vendor/github.com/mitchellh/go-wordwrap/LICENSE.md %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_mitchellh_go-wordwrap_LICENSE.md
cp vendor/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_mitchellh_mapstructure_LICENSE
cp vendor/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_modern-go_concurrent_LICENSE
cp vendor/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_modern-go_reflect2_LICENSE
cp vendor/github.com/onsi/ginkgo/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
cp vendor/github.com/onsi/gomega/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_gomega_LICENSE
cp vendor/github.com/opencontainers/go-digest/LICENSE.code %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_go-digest_LICENSE.code
cp vendor/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_go-digest_LICENSE.docs
cp vendor/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_image-spec_LICENSE
cp vendor/github.com/pborman/uuid/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_pborman_uuid_LICENSE
cp vendor/github.com/pelletier/go-toml/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_pelletier_go-toml_LICENSE
cp vendor/github.com/petar/GoLLRB/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_petar_GoLLRB_LICENSE
cp vendor/github.com/peterbourgon/diskv/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_peterbourgon_diskv_LICENSE
cp vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_pkg_errors_LICENSE
cp vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_pmezard_go-difflib_LICENSE
cp vendor/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_golang_LICENSE
cp vendor/github.com/prometheus/client_golang/NOTICE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_golang_NOTICE
cp vendor/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_model_LICENSE
cp vendor/github.com/prometheus/client_model/ruby/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_model_ruby_LICENSE
cp vendor/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_common_LICENSE
cp vendor/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_procfs_LICENSE
cp vendor/github.com/russross/blackfriday/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_russross_blackfriday_LICENSE.txt
cp vendor/github.com/shazow/go-diff/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_shazow_go-diff_LICENSE
cp vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_sirupsen_logrus_LICENSE
cp vendor/github.com/spf13/afero/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_afero_LICENSE.txt
cp vendor/github.com/spf13/cast/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cast_LICENSE
cp vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cobra_LICENSE.txt
cp vendor/github.com/spf13/cobra/cobra/cmd/testdata/LICENSE.golden %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cobra_cobra_cmd_testdata_LICENSE.golden
cp vendor/github.com/spf13/jwalterweatherman/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_jwalterweatherman_LICENSE
cp vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_pflag_LICENSE
cp vendor/github.com/spf13/viper/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_viper_LICENSE
cp vendor/github.com/stretchr/objx/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_objx_LICENSE
cp vendor/github.com/stretchr/testify/LICENCE.txt %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_testify_LICENCE.txt
cp vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_testify_LICENSE
cp vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_crypto_LICENSE
cp vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_net_LICENSE
cp vendor/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_oauth2_LICENSE
cp vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_sys_LICENSE
cp vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_text_LICENSE
cp vendor/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_golang.org_x_time_LICENSE
cp vendor/google.golang.org/appengine/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_google.golang.org_appengine_LICENSE
cp vendor/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_inf.v0_LICENSE
cp vendor/gopkg.in/mgo.v2/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_LICENSE
cp vendor/gopkg.in/mgo.v2/bson/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_bson_LICENSE
cp vendor/gopkg.in/mgo.v2/internal/json/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_internal_json_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_square_go-jose.v2_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/json/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_yaml.v2_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/ksonnet/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
cp vendor/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_api_LICENSE
cp vendor/k8s.io/apiextensions-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_apiextensions-apiserver_LICENSE
cp vendor/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_apimachinery_LICENSE
cp vendor/k8s.io/apiserver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_apiserver_LICENSE
cp vendor/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_client-go_LICENSE
cp vendor/k8s.io/helm/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_helm_LICENSE
cp vendor/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kube-openapi_LICENSE
cp vendor/k8s.io/kubernetes/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_LICENSE
cp vendor/k8s.io/kubernetes/cluster/juju/layers/kubeapi-load-balancer/copyright %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubeapi-load-balancer_copyright
cp vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-master/copyright %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubernetes-master_copyright
cp vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-worker/copyright %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubernetes-worker_copyright
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_api_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apiextensions-apiserver_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apimachinery_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apiserver_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_client-go_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_code-generator_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_kube-aggregator_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_metrics_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_sample-apiserver_LICENSE
cp vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_sample-controller_LICENSE
cp vendor/k8s.io/kubernetes/third_party/forked/golang/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_golang_LICENSE
cp vendor/k8s.io/kubernetes/third_party/forked/gonum/graph/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_gonum_graph_LICENSE
cp vendor/k8s.io/kubernetes/third_party/forked/shell2junit/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_shell2junit_LICENSE
cp vendor/k8s.io/kubernetes/third_party/htpasswd/COPYING %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_htpasswd_COPYING
cp vendor/k8s.io/kubernetes/third_party/intemp/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_intemp_LICENSE
cp vendor/k8s.io/kubernetes/third_party/swagger-ui/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_swagger-ui_LICENSE
cp vendor/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_k8s.io_utils_LICENSE
cp vendor/vbom.ml/util/LICENSE %{buildroot}/usr/share/package-licenses/ksonnet/vendor_vbom.ml_util_LICENSE
true
## install_append content
install -d %{buildroot}/usr/bin
install -p -m 755 /go/bin/ks %{buildroot}/usr/bin/ks
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ks

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ksonnet/LICENSE
/usr/share/package-licenses/ksonnet/vendor_cloud.google.com_go_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_Azure_go-ansiterm_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_Azure_go-autorest_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_COPYING
/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_toml-test-decoder_COPYING
/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_toml-test-encoder_COPYING
/usr/share/package-licenses/ksonnet/vendor_github.com_BurntSushi_toml_cmd_tomlv_COPYING
/usr/share/package-licenses/ksonnet/vendor_github.com_GeertJohan_go.rice_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_MakeNowJust_heredoc_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_Masterminds_semver_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_Masterminds_sprig_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_PuerkitoBio_purell_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_PuerkitoBio_urlesc_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_aokoli_goutils_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_asaskevich_govalidator_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_beorn7_perks_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_blang_semver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_cenkalti_backoff_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
/usr/share/package-licenses/ksonnet/vendor_github.com_daaku_go.zipexe_license
/usr/share/package-licenses/ksonnet/vendor_github.com_davecgh_go-spew_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_dgrijalva_jwt-go_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_distribution_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_NOTICE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_contrib_syntax_vim_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_go-connections_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_go-units_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_spdystream_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_docker_spdystream_LICENSE.docs
/usr/share/package-licenses/ksonnet/vendor_github.com_emicklei_go-restful-swagger12_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_emicklei_go-restful_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_evanphx_json-patch_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_exponent-io_jsonpath_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_fatih_camelcase_LICENSE.md
/usr/share/package-licenses/ksonnet/vendor_github.com_fatih_color_LICENSE.md
/usr/share/package-licenses/ksonnet/vendor_github.com_fsnotify_fsnotify_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_ghodss_yaml_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_analysis_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_errors_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_jsonpointer_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_jsonreference_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_loads_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_runtime_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_runtime_middleware_denco_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_spec_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_spec_license.go
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_strfmt_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_swag_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_go-openapi_validate_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_gobwas_glob_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_gogo_protobuf_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_golang_glog_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_golang_groupcache_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_golang_protobuf_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_btree_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-github_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-jsonnet_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_go-querystring_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_gofuzz_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_google_uuid_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_googleapis_gnostic_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_gophercloud_gophercloud_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_gregjones_httpcache_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_hashicorp_golang-lru_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_hashicorp_hcl_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_howeyc_gopass_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_howeyc_gopass_OPENSOLARIS.LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_huandu_xstrings_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_imdario_mergo_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_inconshreveable_mousetrap_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_jonboulle_clockwork_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_json-iterator_go_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_kardianos_osext_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_ksonnet_ksonnet-lib_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_magiconair_properties_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_mailru_easyjson_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_mattn_go-colorable_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_mattn_go-isatty_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_mitchellh_go-wordwrap_LICENSE.md
/usr/share/package-licenses/ksonnet/vendor_github.com_mitchellh_mapstructure_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_modern-go_concurrent_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_modern-go_reflect2_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_onsi_gomega_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_go-digest_LICENSE.code
/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_go-digest_LICENSE.docs
/usr/share/package-licenses/ksonnet/vendor_github.com_opencontainers_image-spec_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_pborman_uuid_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_pelletier_go-toml_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_petar_GoLLRB_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_peterbourgon_diskv_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_pkg_errors_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_pmezard_go-difflib_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_golang_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_golang_NOTICE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_model_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_client_model_ruby_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_common_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_prometheus_procfs_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_russross_blackfriday_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_shazow_go-diff_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_sirupsen_logrus_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_afero_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cast_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cobra_LICENSE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_cobra_cobra_cmd_testdata_LICENSE.golden
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_jwalterweatherman_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_pflag_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_spf13_viper_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_objx_LICENSE
/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_testify_LICENCE.txt
/usr/share/package-licenses/ksonnet/vendor_github.com_stretchr_testify_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_crypto_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_net_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_oauth2_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_sys_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_text_LICENSE
/usr/share/package-licenses/ksonnet/vendor_golang.org_x_time_LICENSE
/usr/share/package-licenses/ksonnet/vendor_google.golang.org_appengine_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_inf.v0_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_bson_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_mgo.v2_internal_json_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_square_go-jose.v2_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_yaml.v2_LICENSE
/usr/share/package-licenses/ksonnet/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
/usr/share/package-licenses/ksonnet/vendor_k8s.io_api_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_apiextensions-apiserver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_apimachinery_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_apiserver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_client-go_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_helm_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kube-openapi_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubeapi-load-balancer_copyright
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubernetes-master_copyright
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_cluster_juju_layers_kubernetes-worker_copyright
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_api_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apiextensions-apiserver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apimachinery_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_apiserver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_client-go_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_code-generator_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_kube-aggregator_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_metrics_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_sample-apiserver_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_staging_src_k8s.io_sample-controller_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_golang_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_gonum_graph_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_forked_shell2junit_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_htpasswd_COPYING
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_intemp_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_kubernetes_third_party_swagger-ui_LICENSE
/usr/share/package-licenses/ksonnet/vendor_k8s.io_utils_LICENSE
/usr/share/package-licenses/ksonnet/vendor_vbom.ml_util_LICENSE
